### ISSUE TITLE
TASK_PARALLELIZE renaming mapplate parameters

### ISSUE THREAD

**Issue by stork119** [stork119/PathwayPackage#108]
mp_key -> mp_id
mp_id -> wellname_id
mp_tag -> wellname_tag

Name of well position in mapplate is defined as follows :
- if args_name exists then well.name = prefix + args_name + suffix
- else well.name = prefix + args_id + suffix

Therefore rename and change function `create_ele_list` in such way: 
```
def create_ele_list(input_path, wells_params):   
    """
    Arguments:
    - input_path - path to directories
    - wells_params - list of base parameters of chosen wells set
    Returns
    - verified_dirst- list of dirs which parameters are present 
                        in wells_params list
    """
    all_dir_list = FM.dir_get_names(input_path)
    verified_dirs = []
    for well in wells_params:
        if any(dir_name == well["mp_tag"] for dir_name in all_dir_list):
                verified_dirs.append(well)
        else:
            logger.error("Unexpected used_value: %s", used_value)
    return verified_dirs
```

**Comment by Setnea** [comment]
1. I changed names of mp_id and mp_tag.
2. I didn't change functions according to our conversation:
    - Using names as id if id is missing is already implemented on read_map_plate level
    - We want to keep the chance to check out both id or tag depends on user preferation (i.e. to allow swaping them during downloading >=2 part experiments.
3. I would strongly prefered to keep mp_key name and do not replace it with mp_id. I think that mp_key name fits better due to the true character of element. In fact mp_id is mp_dict[mp_key][mp_id]. Of course atm we're using well id's (aka mp_id) as our keys to all well parameters, but it might change at some point. Name mp_key is also used in other map_plate functions and it is exacly what we're refering for.

I'm gonna push changes just after testing them with test3.
